### PR TITLE
Feature/build speedup

### PR DESCRIPTION
**Pull request by jenniferboedker**
**Purpose of change**
Speed up the build by reordering the repositories.

**Changes**
The order of the repositories should be maven central, QBiC repositories, liferay repository.
Furthermore, distribution management is specified.

### CODE REVIEW

**Comment by jenniferboedker** [comment]
[Transfer example portlet into qube template generation](https://trello.com/c/nK6fbOkj/14-transfer-example-portlet-into-qube-template-generation)

**Review by sven1103 — CHANGES_REQUESTED** [review]
Maven central needs to be still defined in the repository section.

**Review by sven1103 — APPROVED** [review]
LGTM!

**Comment by jenniferboedker** [comment]
It still says merging is blocked because I didn't address your requested changes 🤔

**Review by sven1103 — APPROVED** [review]
awesome!

**Pull request merged**
