### PR TITLE
add project information file

### PR DESCRIPTION
**Pull request by jenniferboedker**
**Purpose of change**
Add the missing files

**Changes**
Add the `ProjectInfomation.java` file and the `app.properties` file, which is containing the project information

### CODE REVIEW

**Comment by jenniferboedker** [comment]
[Transfer example portlet into qube template generation](https://trello.com/c/nK6fbOkj/14-transfer-example-portlet-into-qube-template-generation)

**Review by sven1103 — APPROVED** [review]
Nice1!

**Comment by sven1103** [comment]
Maybe update the CL, so we dont forget it later

**Review by sven1103 — DISMISSED** [review]
lgtm!

**Review by sven1103 — APPROVED** [review]

**Pull request merged**
