### PR TITLE
Fix .gitignore to ignore vaadin widgetsets in project modules

### PR DESCRIPTION
**Pull request by KochTobi**
**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

- [x] This comment contains a description of changes (with reason)
- [ ] Referenced issue is linked
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated
- [ ] `CHANGELOG.rst` is updated

**Description of changes**
Add all `**/src/main/webapp/VAADIN/widgetsets` folders to the `.gitignore`

### CODE REVIEW

**Comment by Zethson** [comment]
@KochTobi I am happy to see that you are updating the changelog, but qube is based on another tool (cookietemple), which by itself has a bump-version command.
-> It ensures that the version is consistent across changelog & a couple of other files.

I will revert your changelog change and do a version bump.

**Comment by KochTobi** [comment]
@Zethson do I need to update something to use the `.gitignore` for every template?

**Comment by Zethson** [comment]
@KochTobi No.

But you can always try it out yourself :)

Pull this branch again, then run:

`make install`

Next run 

`qube --help`

and you should get 

`Installed version 2.4.0 of qube is newer than the latest release 2.3.0! You are running a nightly version and features may break!`

Now create a project and verify that your change did indeed what you wanted to have.

Also, please make the PR against development :) I could change it now, but just want to make you aware.

Cheers

**Comment by Zethson** [comment]
@sven1103 @KochTobi 

I will make a release after this PR.
I'm a big fan of releasing quick and often.

**Comment by KochTobi** [comment]
This PR is meant to make a patch release from :)

**Comment by Zethson** [comment]
@KochTobi I know.
But we already have 2 changes by @sven1103 lined up, which I will simply include :)

**Comment by Zethson** [comment]
@KochTobi Ahh, I see.
So qube expects "patches" to have the name "patch" in the branch.

@sven1103 changed that for all templates to hotfix.

You could not know about this :)

Well I'll just merge this then and release all of it together.

**Comment by Zethson** [comment]
@KochTobi please remove the draft label when you're ready.

**Comment by KochTobi** [comment]
> @KochTobi Ahh, I see.
> So qube expects "patches" to have the name "patch" in the branch.
> 
> @sven1103 changed that for all templates to hotfix.
> 
> You could not know about this :)
> 
> Well I'll just merge this then and release all of it together.

I like both `patch` and `hotfix` 🤷

**Pull request merged**
