### PR TITLE
Increase oleksiyrudenko/gha-git-credentials version

### LINKED ISSUE #231: Sync will break due to old set-env API -> upgrade git credentials GH actions from v1 to v2
Hi,

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

set-env is already disabled and sync is broken.

Modify v1 to v2

https://github.com/qbicsoftware/qube-cli/blob/master/qube/create/templates/common_files/%7B%7B%20cookiecutter.commonName%20%7D%7D/.github/workflows/sync_project.yml

`        - uses: oleksiyrudenko/gha-git-credentials@v1`

-> 

`        - uses: oleksiyrudenko/gha-git-credentials@v2`

Ensure that this is reflected in all already existing projects.

Cheers
Lukas

### PR DESCRIPTION
**Pull request by KochTobi**
Solves #231

### CODE REVIEW

**Review by Zethson — APPROVED** [review]
LGTM :)

Unfortunately you have to fix that manually for all other projects, since their sync will fail and they cannot correct it themselves.

One of the very rare cases where syncing breaks...

**Comment by KochTobi** [comment]
Thanks :)

**Comment by KochTobi** [comment]
> LGTM :)
> 
> Unfortunately you have to fix that manually for all other projects, since their sync will fail and they cannot correct it themselves.
> 
> One of the very rare cases where syncing breaks...

Where and how can I fix it manually? Do I remove the workflow? How is this done?

**Comment by Zethson** [comment]
You look for this file https://github.com/qbicsoftware/qoffer-2-portlet/blob/master/.github/workflows/sync_project.yml (see here for qoffer2) and apply the same fix

https://github.com/qbicsoftware/qoffer-2-portlet/blob/master/.github/workflows/sync_project.yml#L26

v1 -> v2

Note that this should be done in the master branch.

**Comment by KochTobi** [comment]
For the `data-model-lib` this does not work because the file is not on `master`. How can I proceed here? 
The change is present in `development`

**Comment by Zethson** [comment]
That's fine. Just increase it in ```development```.

**Comment by Zethson** [comment]
@KochTobi I wanted to comment here, but for some reason replied in the issue.

Anyways -> 2. answer is in the issue thread.

**Pull request merged**
